In [1]:
import os
import pandas as pd
import numpy as np

user_folder = os.path.expanduser('~')
data_folder = os.path.join(user_folder, 'E:/git/myKaggle/Toxic_Comment')
files = os.listdir(data_folder)
files

['.ipynb_checkpoints',
 'beginner.py',
 'blend_of_blends_1.py',
 'data_description.md',
 'keras_beginner.ipynb',
 'keras_blend.ipynb',
 'LGB_GRU_LR_LSTM_NB-SVM_Average_Ensemble.py',
 'LightGBM_with_Select_K_Best_on_TFIDF.py',
 'logistic_regression.py',
 'myblends.ipynb',
 'myblends_random.ipynb',
 'myKeras_epoch2_submission.csv',
 'myKeras_submission_1.csv',
 'myKeras_submission_2.csv',
 'myKeras_submission_3.csv',
 'myKeras_submission_4.csv',
 'mykeras_with_prepro',
 'myKeras_with_preprocessing.ipynb',
 'myNewbies.ipynb',
 'myNewbies_result.csv',
 'NB_SVM.ipynb',
 'Pooled_GRU_plus_GloVe.py',
 'tensorflow_officialTutorial.ipynb',
 'tf_officialTutorial_MNISTforMLBeginners.ipynb',
 'toxic_one_more_b8bce2.py',
 'Untitled.ipynb',
 'Untitled1.ipynb']

In [6]:
K1 = pd.read_csv(os.path.join(data_folder, files[12]))
K2 = pd.read_csv(os.path.join(data_folder, files[13]))
K3 = pd.read_csv(os.path.join(data_folder, files[14]))
K4 = pd.read_csv(os.path.join(data_folder, files[15]))


# ave = pd.read_csv(os.path.join(data_folder, files[5])) # 0.9823


weights = pd.Series([0.25]*4)

In [7]:
# Bojan suggests scaling with min-max to make sure that all the submissions have
# orderings that can be compared. Since our metric is AUC, this is okay and may
# improve performance.

from sklearn.preprocessing import minmax_scale
labels = ["toxic", "severe_toxic", "obscene", "threat", "insult", "identity_hate"]

In [9]:
for label in labels:
    print(label)
    print(np.corrcoef([K1[label], K2[label], K3[label], K4[label]]))

toxic
[[1.         0.97690888 0.97877637 0.97877637]
 [0.97690888 1.         0.97822737 0.97822737]
 [0.97877637 0.97822737 1.         1.        ]
 [0.97877637 0.97822737 1.         1.        ]]
severe_toxic
[[1.         0.93925194 0.91594614 0.91594614]
 [0.93925194 1.         0.92071867 0.92071867]
 [0.91594614 0.92071867 1.         1.        ]
 [0.91594614 0.92071867 1.         1.        ]]
obscene
[[1.         0.97782013 0.97691905 0.97691905]
 [0.97782013 1.         0.97532997 0.97532997]
 [0.97691905 0.97532997 1.         1.        ]
 [0.97691905 0.97532997 1.         1.        ]]
threat
[[1.         0.66257665 0.82300698 0.82300698]
 [0.66257665 1.         0.63386948 0.63386948]
 [0.82300698 0.63386948 1.         1.        ]
 [0.82300698 0.63386948 1.         1.        ]]
insult
[[1.         0.97498708 0.97498248 0.97498248]
 [0.97498708 1.         0.97130601 0.97130601]
 [0.97498248 0.97130601 1.         1.        ]
 [0.97498248 0.97130601 1.         1.        ]]
identity_hate


In [10]:
import copy
submission = copy.deepcopy(K1)

In [11]:
datasets = [K1, K2, K3, K4]
datasets_rmid = [df.drop('id', axis=1) for df in datasets]

In [12]:
result = [weights[i]*datasets_rmid[i] for i in range(len(datasets))]
result = sum(result)/sum(weights)

In [13]:
submission.to_csv('keras_ave_result.csv', index=False)

In [14]:
submission.head(3)

id     toxic  severe_toxic   obscene    threat    insult  \
0  00001cee341fdb12  0.999079  4.258385e-01  0.970865  0.074509  0.891107   
1  0000247867823ef7  0.001025  9.470544e-07  0.000234  0.000008  0.000162   
2  00013b17ad220c46  0.000898  1.196599e-06  0.000222  0.000007  0.000159   

   identity_hate  
0       0.203512  
1       0.000053  
2       0.000056